(()=>{
  const $=id=>document.getElementById(id),projectId=new URLSearchParams(location.search).get('project');
  let project,session=null,turn=1,busy=false;
  async function api(action,payload){const r=await fetch(`/api/prepared-agents/${projectId}${action?'/'+action:''}`,payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to complete this request');return data;}
  function say(who,text,visitor=false){const p=document.createElement('div');p.className='bubble'+(visitor?' visitor':'');const name=document.createElement('strong');name.textContent=who;p.append(name,document.createTextNode(text));$('conversation').append(p);$('conversation').scrollTop=$('conversation').scrollHeight;}
  $('fresh').onclick=()=>{if(busy)return;session=null;turn=1;$('conversation').replaceChildren();$('handoff').textContent='No request yet.';$('status').textContent='Fresh conversation. No previous customer details.';$('send').disabled=false;$('message').focus();};
  $('chat').onsubmit=async event=>{event.preventDefault();if(busy||!project)return;const message=$('message').value.trim();if(!message)return;busy=true;$('send').disabled=true;$('fresh').disabled=true;$('message').disabled=true;
    const started=Date.now(),update=()=>{$('status').textContent=`${project.fields.x_agent_name} is answering… ${Math.floor((Date.now()-started)/1000)} seconds`;};update();const timer=setInterval(update,1000);
    try{if(!session)session=await api('text-session',{owner_requested:true,candidate_sha256:project.text_candidate.candidate_sha256});say('You',message,true);const reply=await api('text-turn',{session_id:session.session_id,message,expected_turn:turn,owner_requested:true});say(project.fields.x_agent_name,reply.text);$('handoff').textContent=JSON.stringify(reply.output.handoff,null,2);$('message').value='';turn++;$('status').textContent=turn>7?'Conversation complete. Start a fresh conversation to continue.':'Ready for your next question.';$('send').disabled=turn>7;
    }catch(error){$('status').textContent=error.message+' Start a fresh conversation after resolving the issue.';
    }finally{clearInterval(timer);busy=false;$('fresh').disabled=false;$('message').disabled=false;}};
  (async()=>{try{if(!/^project-[a-f0-9]{24}$/.test(projectId||''))throw Error('Open an agent from the Factory.');project=await api('');if(!project.mission_id||!project.text_candidate)throw Error('This agent needs a reviewed build. Return to the Factory.');document.title=project.fields.x_agent_name;$('name').textContent=project.fields.x_agent_name;$('company').textContent=project.fields.client_name;if(project.portrait){$('portrait').src=project.portrait;$('portrait').hidden=false;}const ephemeral=new URLSearchParams(location.search).get('mode')==='ephemeral-test';if(ephemeral)document.querySelector('footer').textContent='Ephemeral browser rehearsal · deterministic fixture · zero model/provider calls. Use fictional data only. Refreshing starts a fresh conversation; no repository, ANAM, Hermes, Vercel, or production writes occur.';$('status').textContent='Ready. Ask a question below.';$('send').disabled=false;$('fresh').disabled=false;}catch(error){$('name').textContent='Unable to open this build';$('status').textContent=error.message;}})();
})();
