const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const base=process.env.STUDIO_TEST_URL;
if(!base||process.env.STUDIO_TEST_ISOLATED!=='1')throw Error('Use the isolated Python test wrapper.');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.STUDIO_TEST_CHROMIUM});
 const page=await browser.newPage({viewport:{width:1440,height:1050},reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue():route.abort());
 const out=path.resolve('outputs/prepared-agent-qa-20260905');fs.mkdirSync(out,{recursive:true});
 try{
  await page.goto(base,{waitUntil:'networkidle'});
  await page.locator('#idea-seed').fill('Keep my original opportunity when I leave the example.');
  await page.locator('#load-morning-example').click();
  await page.waitForFunction(()=>document.querySelector('#commission-agent-name').value==='Ava');
  await page.locator('#leave-example').click();
  assert.equal(await page.locator('#idea-seed').inputValue(),'Keep my original opportunity when I leave the example.');
  assert(await page.locator('#idea-seed').isVisible());
  assert(await page.locator('#commissioning-form').isHidden());
  await page.locator('#idea-seed').fill('A moving inquiry assistant for Sample Moving Company. Help customers plan a move and prepare a staff handoff.');
  await page.locator('details.idea-extra > summary').click();
  await page.locator('#idea-company').fill('Sample Moving Company');
  await page.locator('#idea-website').fill('https://example.com/');
  await page.locator('#idea-source-files').setInputFiles({name:'owner-notes.md',mimeType:'text/markdown',buffer:Buffer.from('Owner-supplied source material for a moving inquiry guide. Draft facts require review before approval.')});
  await page.getByText('owner-notes.md',{exact:true}).waitFor();
  const pixel=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=4;c.height=4;return c.toDataURL('image/png').split(',')[1];});
  await page.locator('#idea-source-files').setInputFiles({name:'reference.png',mimeType:'image/png',buffer:Buffer.from(pixel,'base64')});
  await page.getByLabel('Describe the image for the specialists (required; no OCR)').fill('A neutral visual reference. It is not evidence of company services.');
  await page.locator('#prepare-idea').click();
  await page.locator('#research-idea').waitFor({state:'visible'});
  await page.waitForFunction(()=>!document.querySelector('#research-idea').disabled);
  assert(await page.locator('#use-idea').isHidden(),'Manual bypass stays collapsed');
  assert(await page.locator('#commissioning-form').isHidden(),'No empty manual knowledge form in automatic preparation');
  await page.evaluate(()=>{window.forcedScrolls=0;const original=Element.prototype.scrollIntoView;Element.prototype.scrollIntoView=function(...args){window.forcedScrolls++;return original.apply(this,args);};});
  await page.locator('#research-idea').click();
  await page.locator('#prepared-system-prompt').waitFor({state:'visible',timeout:20000});
  assert.equal(await page.locator('#prepared-agent .prepared-knowledge details').count(),1);
  assert.match(await page.locator('#prepared-system-prompt').inputValue(),/\[K-0001\]/);
  assert.equal(await page.locator('#prepared-approve').isDisabled(),true);
  assert.equal(await page.locator('#prepared-build').count(),0);
  assert.equal(await page.evaluate(()=>window.forcedScrolls),0,'Preparation must not force scroll');
  await page.getByText('Agent picture · upload your own',{exact:true}).click();
  const detailedPortrait=await page.evaluate(()=>{
    const c=document.createElement('canvas');c.width=512;c.height=512;
    const ctx=c.getContext('2d'),pixels=ctx.createImageData(512,512);
    let seed=12345;for(let i=0;i<pixels.data.length;i++){seed=(1664525*seed+1013904223)>>>0;pixels.data[i]=i%4===3?255:seed>>>24;}
    ctx.putImageData(pixels,0,0);return c.toDataURL('image/png').split(',')[1];
  });
  assert(Buffer.from(detailedPortrait,'base64').length>40000,'Exercise a detailed image above the storage limit');
  await page.getByLabel('Upload agent picture').setInputFiles({name:'portrait.png',mimeType:'image/png',buffer:Buffer.from(detailedPortrait,'base64')});
  await page.getByText('Picture saved. Continue with your next step above.',{exact:true}).waitFor();
  await page.locator('#prepared-agent').screenshot({path:path.join(out,'review-desktop.png')});
  const before=await page.locator('#prepared-system-prompt').inputValue();
  await page.locator('#prepared-system-prompt').fill(before+'\nOwner refinement: concise and practical.');
  await page.locator('#prepared-attestation').check();
  assert.equal(await page.locator('#prepared-approve').isDisabled(),true,'Unsaved edits cannot be approved');
  await page.getByRole('button',{name:'Save prompt edits',exact:true}).click();
  await page.reload({waitUntil:'networkidle'});
  await page.getByRole('button',{name:'Reopen my prepared agent',exact:true}).click();
  await page.locator('#prepared-system-prompt').waitFor({state:'visible'});
  assert.match(await page.locator('#prepared-system-prompt').inputValue(),/Owner refinement/);
  const savedPortrait=await page.locator('#prepared-agent img.prepared-portrait').getAttribute('src');
  assert(savedPortrait.startsWith('data:image/png;base64,'),'Portrait survives reopening');
  await page.locator('#prepared-attestation').check();
  await page.locator('#prepared-approve').click();
  await page.locator('#prepared-build').waitFor({state:'visible'});
  await page.locator('#prepared-build').click();
  await page.getByRole('heading',{name:'Talk to your agent',exact:true}).waitFor({state:'visible',timeout:30000});
  assert.equal(await page.locator('#prepared-conversation img').getAttribute('src'),savedPortrait);
  await page.getByRole('button',{name:'2 · Check agent quality ↓',exact:true}).click();
  assert(await page.locator('#prepared-quality').evaluate(e=>e.open),'Guide opens the quality check');
  await page.getByRole('button',{name:'1 · Try your agent ↓',exact:true}).click();
  await page.getByRole('textbox',{name:'Message for the live text test',exact:true}).fill('What moving services are available?');
  await page.getByRole('button',{name:'Send to Luna',exact:true}).click();
  await page.locator('.prepared-model-transcript').getByText(/reviewed information lists packing/).waitFor();
  await page.getByRole('button',{name:'Start fresh session',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.prepared-model-transcript p').length===0);
  assert.equal(await page.locator('.prepared-model-transcript p').count(),0,'Fresh session clears previous response');
  const popupPromise=page.waitForEvent('popup');
  await page.locator('.prepared-guide a').click();
  const app=await popupPromise;await app.waitForLoadState('networkidle');
  await app.locator('#send:not([disabled])').waitFor();
  assert.equal(await app.locator('#portrait').getAttribute('src'),savedPortrait);
  await app.locator('#message').fill('What moving services are available?');await app.locator('#send').click();
  await app.locator('#conversation').getByText(/reviewed information lists packing/).waitFor();
  await app.locator('#fresh').click();assert.equal(await app.locator('#conversation .bubble').count(),0);
  await app.screenshot({path:path.join(out,'standalone-app.png')});await app.close();
  await page.locator('.prepared-settings > summary').click();
  await page.getByText('Technical tools · local knowledge checker',{exact:true}).click();
  await page.getByRole('button',{name:'Open technical knowledge checker',exact:true}).click();
  await page.waitForTimeout(400);
  assert.equal(errors.length,0,errors.join('\n'));
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(250);
  await page.screenshot({path:path.join(out,'mobile-full.png'),fullPage:true});
  const overflow=await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(e=>[e.tagName,e.id,e.className,e.getBoundingClientRect().width]));
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile overflow '+JSON.stringify(overflow));
  await page.locator('#prepared-agent').screenshot({path:path.join(out,'review-mobile.png')});
  const projectId=await page.evaluate(()=>localStorage.getItem('x-factory-prepared-project'));
  const project=await (await page.request.get(`${base}/api/prepared-agents/${projectId}`)).json();
  const inbox=await browser.newPage({viewport:{width:1440,height:1050}});
  await inbox.route('**/api/hunter/inbox',async route=>{await new Promise(r=>setTimeout(r,600));await route.fulfill({json:{leads:[{prospect_id:'test-stale',company_name:'Sample Moving Company',website:'https://example.com',wedge:'moving_relocation',score:80,reverification_required:true,blockers:[],status:'HOLD'}]}});});
  await inbox.route('**/api/prepared-from-hunter',async route=>{await new Promise(r=>setTimeout(r,1200));await route.fulfill({json:{...project,status:'NEEDS_REVIEW',mission_id:null,approval:null,message:'Prepared draft ready for owner review.'}});});
  await inbox.goto(base,{waitUntil:'networkidle'});
  await inbox.locator('[data-studio-target="hunter"]').click();
  await inbox.waitForFunction(()=>!document.querySelector('#refresh-hunter-inbox').disabled);
  await inbox.locator('#refresh-hunter-inbox').click();
  assert.equal(await inbox.locator('#refresh-hunter-inbox').innerText(),'CHECKING INBOX…');
  await inbox.locator('#hunter-inbox-status').getByText(/Inbox checked/).waitFor();
  assert.equal(await inbox.getByRole('button',{name:/PREPARE HUNTER REFRESH|COPY REQUEST/}).count(),0);
  await inbox.getByRole('button',{name:'RESEARCH & PREPARE THIS AGENT →',exact:true}).click();
  assert(await inbox.locator('.hunter-operation-progress').innerText().then(t=>t.includes('Starting fresh company research')));
  await inbox.locator('#prepared-agent').getByText('Prepared draft ready for owner review.',{exact:true}).waitFor();
  assert(await inbox.locator('#hunter-inbox').isHidden(),'The old lead card must not compete with the open preparation workspace');
  await inbox.screenshot({path:path.join(out,'hunter-feedback.png'),fullPage:true});
  await inbox.close();
  console.log('PASS: populated unapproved draft → edit → reopen → approve → actual local build → candidate; desktop/mobile; no forced prep scroll; zero provider calls.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
